Name: CVE-2014-3730
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-3730
Phase: Assigned (20140514)
Category: 
Reference: MLIST:[oss-security] 20140514 CVE Reuest: Django: Malformed URLs from user input incorrectly validated
Reference: URL:http://www.openwall.com/lists/oss-security/2014/05/14/10
Reference: MLIST:[oss-security] 20140514 Re: CVE Reuest: Django: Malformed URLs from user input incorrectly validated
Reference: URL:http://www.openwall.com/lists/oss-security/2014/05/15/3
Reference: CONFIRM:https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/
Reference: DEBIAN:DSA-2934
Reference: URL:http://www.debian.org/security/2014/dsa-2934
Reference: SUSE:openSUSE-SU-2014:1132
Reference: URL:http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
Reference: UBUNTU:USN-2212-1
Reference: URL:http://ubuntu.com/usn/usn-2212-1
Reference: BID:67410
Reference: URL:http://www.securityfocus.com/bid/67410
Reference: SECUNIA:61281
Reference: URL:http://secunia.com/advisories/61281

The django.util.http.is_safe_url function in Django 1.4 before 1.4.13,
1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not
properly validate URLs, which allows remote attackers to conduct open
redirect attacks via a malformed URL, as demonstrated by
"http:\djangoproject.com."


Current Votes:
None (candidate not yet proposed)


