Name: CVE-2014-1624
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1624
Phase: Assigned (20140121)
Category: 
Reference: MLIST:[oss-security] 20140121 Fwd: [Python-modules-team] Bug#736247: python-xdg: get_runtime_dir(strict=False): insecure use of /tmp
Reference: URL:http://www.openwall.com/lists/oss-security/2014/01/21/3
Reference: MLIST:[oss-security] 20140121 Re: Fwd: [Python-modules-team] Bug#736247: python-xdg: get_runtime_dir(strict=False): insecure use of /tmp
Reference: URL:http://www.openwall.com/lists/oss-security/2014/01/21/4
Reference: MISC:http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736247
Reference: BID:65042
Reference: URL:http://www.securityfocus.com/bid/65042
Reference: XF:pythonxdg-cve20141624-symlink(90618)
Reference: URL:https://exchange.xforce.ibmcloud.com/vulnerabilities/90618

Race condition in the xdg.BaseDirectory.get_runtime_dir function in
python-xdg 0.25 allows local users to overwrite arbitrary files by
pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a
victim-owned location, then replacing it with a symlink to an
attacker-controlled location once the get_runtime_dir function is
called.


Current Votes:
None (candidate not yet proposed)


